name: telegram message
on:
  workflow_dispatch:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-node@v1

    - uses: microsoft/playwright-github-action@v1

    - name: Install dependencies
      run: npm install

    - name: Run Script
      id: run_script_check
      run: echo "##[set-output name=npm;]$(node index.js)"

    - name: send custom message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Checking for Bupa Locations in [Sydney - NSW]:
          ${{ steps.run_script_check.outputs.npm }}

    - name: send custom message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO_DAYSE }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Checking for Bupa Locations in [Sydney - NSW]:
          ${{ steps.run_script_check.outputs.npm }}
